@OpenIddictClientCredentialServer_HostAddress = http://localhost:5164
@OpenIddictClientCredentialServer_HostAddress_SSL = https://localhost:7196

GET {{OpenIddictClientCredentialServer_HostAddress}}/weatherforecast/
Accept: application/json

### Get access token with client credentials flow
POST {{OpenIddictClientCredentialServer_HostAddress_SSL}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=api.inventory
&client_secret=388D45FA-B36B-4988-BA59-B187D329C207
&scope=openid
