@client_id = api.inventory
@client_secret = 388D45FA-B36B-4988-BA59-B187D329C207
@identity_server = https://localhost:7196
@OpenIddictClientCredentialResource_HostAddress = http://localhost:5281

### Retrieve access token
# @name tokenrequest
POST {{identity_server}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=api.inventory
&client_secret=388D45FA-B36B-4988-BA59-B187D329C207
&scope=openid

###
@token = {{tokenrequest.response.body.access_token}}
###

### Get Weather
GET {{OpenIddictClientCredentialResource_HostAddress}}/weatherforecast/
Authorization: Bearer {{token}}
Accept: application/json
###
